version: '3.9'

services:
  mongoimport:
    image: mongo
    volumes:
      - ./mongo/data/users.json:/src/data/users.json
    command: mongoimport --host mongo --username root --password pwd --db admin --collection users --file /src/data/users.json --jsonArray
    networks:
      - mongodb
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    depends_on:
      - mongoimport
    networks:
      - mongodb

  order-search-service:
    build:
      context: ./order-search-service
      dockerfile: Dockerfile
    image: order-search-service
    ports:
      - 8083:8083
    networks:
      - reactive-services

  product-info-service:
    build:
      context: ./product-info-service
      dockerfile: Dockerfile
    image: product-info-service
    ports:
      - 8082:8082
    networks:
      - reactive-services

  order-product-consumer:
    build:
      context: ./order-product-consumer
      dockerfile: Dockerfile
    image: order-product-consumer
    ports:
      - 8084:8084
    depends_on:
      - mongo
      - product-info-service
      - order-search-service
    networks:
      - mongodb
      - reactive-services

networks:
  mongodb:
    driver: bridge
  reactive-services:
    driver: bridge