management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
spring:
  data:
    mongodb:
      database: admin
      port: 27017
      username: root
      password: pwd
services:
  order-search: "http://localhost:8083/orderSearchService"
  product-info: "http://localhost:8082/productInfoService"

loggin:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

server:
  port: 8084