management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
spring:
  data:
    mongodb:
      database: admin
      port: 27017
      username: root
      password: pwd
services:
  order-search: "http://127.0.0.1:8083/orderSearchService"
  product-info: "http://127.0.0.1:8082/productInfoService"