management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
logging:
  level:
    root: INFO
server:
  port: 8082